---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 2


provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  chef_license: "accept-no-persist"
  product_name: chef
  product_version: 14.12.3


verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[install_node::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
